function getSolidityToolParts(tool: HTMLElement) {
	return {
		name: tool.querySelector<HTMLInputElement>("[data-token-name]"),
		symbol: tool.querySelector<HTMLInputElement>("[data-token-symbol]"),
		supply: tool.querySelector<HTMLInputElement>("[data-token-supply]"),
		decimals: tool.querySelector<HTMLInputElement>("[data-token-decimals]"),
		owner: tool.querySelector<HTMLInputElement>("[data-owner-address]"),
		output: tool.querySelector<HTMLTextAreaElement>("[data-output]"),
		status: tool.querySelector<HTMLElement>("[data-status]"),
		displaySupply: tool.querySelector<HTMLElement>("[data-display-supply]"),
		rawSupply: tool.querySelector<HTMLElement>("[data-raw-supply]"),
		riskLevel: tool.querySelector<HTMLElement>("[data-risk-level]"),
	};
}

function setSolidityStatus(
	tool: HTMLElement,
	message: string,
	isError = false,
) {
	const { status } = getSolidityToolParts(tool);
	if (!status) return;
	status.textContent = message;
	status.classList.toggle("text-[var(--primary)]", !isError);
	status.classList.toggle("text-red-500", isError);
}

function normalizeTokenName(value: string) {
	return value.trim().replace(/\s+/g, " ").slice(0, 48) || "Kris Web3 Demo";
}

function normalizeTokenSymbol(value: string) {
	let symbol = value
		.trim()
		.toUpperCase()
		.replace(/[^A-Z0-9]/g, "")
		.slice(0, 12);
	if (/^\d/.test(symbol)) symbol = `T${symbol}`;
	return symbol || "KWD";
}

function parseTokenSupply(value: string) {
	const normalized = value.trim().replace(/,/g, "");
	if (!/^\d+(\.\d+)?$/.test(normalized)) {
		throw new Error("发行量只能填写正数");
	}
	return normalized;
}

function parseTokenDecimals(value: string) {
	const decimals = Number(value.trim());
	if (!Number.isInteger(decimals) || decimals < 0 || decimals > 36) {
		throw new Error("小数位建议填写 0 到 36 之间的整数");
	}
	return decimals;
}

function toRawSupply(supply: string, decimals: number) {
	const [integerPart, decimalPart = ""] = supply.split(".");
	if (decimalPart.length > decimals) {
		throw new Error("发行量的小数精度不能超过所选小数位");
	}
	const paddedDecimal = decimalPart.padEnd(decimals, "0").slice(0, decimals);
	const raw = `${integerPart}${paddedDecimal}`.replace(/^0+(?=\d)/, "");
	return raw || "0";
}

function escapeSolidityString(value: string) {
	return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function normalizeOwnerAddress(value: string) {
	const owner = value.trim();
	if (!owner) return "";
	if (!/^0x[a-fA-F0-9]{40}$/.test(owner)) {
		throw new Error("部署接收地址需要是 0x 开头的 40 位十六进制地址");
	}
	return owner;
}

function formatCompactNumber(value: string) {
	const [integerPart, decimalPart] = value.split(".");
	const grouped = integerPart.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
	return decimalPart ? `${grouped}.${decimalPart}` : grouped;
}

function getOwnerLine(owner: string) {
	if (!owner.trim()) return "        _mint(msg.sender, initialSupply);";
	return `        _mint(${owner.trim()}, initialSupply);`;
}

function buildSolidityContract(params: {
	name: string;
	symbol: string;
	supply: string;
	decimals: number;
	rawSupply: string;
	owner: string;
}) {
	const tokenName = escapeSolidityString(params.name);
	const tokenSymbol = escapeSolidityString(params.symbol);
	return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

/// @notice Learning template generated by blog.hiauto.me.
/// @dev Use this as a testnet starter. Audit before any mainnet deployment.
contract ${params.symbol}Token is ERC20 {
    uint8 private immutable customDecimals;

    constructor() ERC20("${tokenName}", "${tokenSymbol}") {
        customDecimals = ${params.decimals};
        uint256 initialSupply = ${params.rawSupply};
${getOwnerLine(params.owner)}
    }

    function decimals() public view override returns (uint8) {
        return customDecimals;
    }
}

/*
Token summary
- Display name: ${params.name}
- Symbol: ${params.symbol}
- Display supply: ${formatCompactNumber(params.supply)}
- Raw smallest units: ${params.rawSupply}

Suggested next steps
1. Install OpenZeppelin contracts.
2. Deploy to a testnet such as Sepolia.
3. Verify the contract source on the block explorer.
4. Review owner, minting, pausing, fees, liquidity, and legal risk before mainnet.
*/`;
}

function generateSolidityContract(tool: HTMLElement) {
	const parts = getSolidityToolParts(tool);
	if (
		!parts.name ||
		!parts.symbol ||
		!parts.supply ||
		!parts.decimals ||
		!parts.output
	) {
		return;
	}

	try {
		const name = normalizeTokenName(parts.name.value);
		const symbol = normalizeTokenSymbol(parts.symbol.value);
		const supply = parseTokenSupply(parts.supply.value);
		const decimals = parseTokenDecimals(parts.decimals.value);
		const rawSupply = toRawSupply(supply, decimals);
		const owner = normalizeOwnerAddress(parts.owner?.value ?? "");

		parts.name.value = name;
		parts.symbol.value = symbol;
		parts.supply.value = supply;
		parts.decimals.value = String(decimals);
		if (parts.owner) parts.owner.value = owner;
		parts.output.value = buildSolidityContract({
			name,
			symbol,
			supply,
			decimals,
			rawSupply,
			owner,
		});

		if (parts.displaySupply)
			parts.displaySupply.textContent = formatCompactNumber(supply);
		if (parts.rawSupply) parts.rawSupply.textContent = rawSupply;
		if (parts.riskLevel) parts.riskLevel.textContent = "学习实验";
		setSolidityStatus(tool, "Solidity 模板已生成");
	} catch (error) {
		parts.output.value = "";
		setSolidityStatus(
			tool,
			error instanceof Error ? error.message : "参数不正确，请检查输入",
			true,
		);
	}
}

async function copySolidityContract(tool: HTMLElement) {
	const { output } = getSolidityToolParts(tool);
	if (!output?.value) {
		setSolidityStatus(tool, "没有可复制的合约代码", true);
		return;
	}

	try {
		await navigator.clipboard.writeText(output.value);
		setSolidityStatus(tool, "合约代码已复制");
	} catch {
		setSolidityStatus(tool, "复制失败，请手动选中代码复制", true);
	}
}

function clearSolidityTool(tool: HTMLElement) {
	const parts = getSolidityToolParts(tool);
	if (parts.name) parts.name.value = "";
	if (parts.symbol) parts.symbol.value = "";
	if (parts.supply) parts.supply.value = "";
	if (parts.decimals) parts.decimals.value = "18";
	if (parts.owner) parts.owner.value = "";
	if (parts.output) parts.output.value = "";
	if (parts.displaySupply) parts.displaySupply.textContent = "--";
	if (parts.rawSupply) parts.rawSupply.textContent = "--";
	if (parts.riskLevel) parts.riskLevel.textContent = "学习实验";
	setSolidityStatus(tool, "已清空");
}

function loadSoliditySample(tool: HTMLElement) {
	const parts = getSolidityToolParts(tool);
	if (parts.name) parts.name.value = "Kris Web3 Demo";
	if (parts.symbol) parts.symbol.value = "KWD";
	if (parts.supply) parts.supply.value = "1000000";
	if (parts.decimals) parts.decimals.value = "18";
	if (parts.owner) parts.owner.value = "";
	generateSolidityContract(tool);
}

document.addEventListener("input", (event) => {
	const target = event.target;
	if (!(target instanceof Element)) return;

	const tool = target.closest<HTMLElement>("solidity-starter-tool");
	if (!tool) return;
	generateSolidityContract(tool);
});

document.addEventListener("click", (event) => {
	const target = event.target;
	if (!(target instanceof Element)) return;

	const actionButton = target.closest<HTMLElement>(
		"solidity-starter-tool [data-action]",
	);
	const tool = actionButton?.closest<HTMLElement>("solidity-starter-tool");
	const action = actionButton?.dataset.action;
	if (!tool || !action) return;

	if (action === "generate") generateSolidityContract(tool);
	if (action === "copy") void copySolidityContract(tool);
	if (action === "clear") clearSolidityTool(tool);
	if (action === "sample") loadSoliditySample(tool);
});

function initSolidityStarterTools() {
	document
		.querySelectorAll<HTMLElement>("solidity-starter-tool")
		.forEach((tool) => {
			generateSolidityContract(tool);
		});
}

initSolidityStarterTools();

if (window?.swup?.hooks) {
	window.swup.hooks.on("page:view", initSolidityStarterTools);
} else {
	document.addEventListener("swup:enable", () => {
		window.swup?.hooks.on("page:view", initSolidityStarterTools);
	});
}
